name: Build & FTP Deploy

on:
  push:
    branches: [ main ]             # ← mainにpushで自動デプロイ（不要なら消してOK）
  workflow_dispatch:
    inputs:
      reason:
        description: "Optional reason for the manual run"
        required: false
        default: "manual"
  repository_dispatch:
    types: [ microcms-update ]     # ← microCMS側のevent_typeと一致させる

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        # ビルド時にmicroCMSの環境変数が必要な場合だけSecretsを渡す
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          MICROCMS_API_VERSION: ${{ secrets.MICROCMS_API_VERSION }}
          MICROCMS_BLOG_ENDPOINT: ${{ secrets.MICROCMS_BLOG_ENDPOINT }}
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:     ${{ secrets.FTP_SERVER }}       
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          local-dir:  ./dist/
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}    
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false
          protocol: ftps
          security: loose